package avro

import "github.com/stealthly/go-avro"

type SlaveMetrics struct {
	SlaveID   string
	Hostname  string
	Port      int32
	Namespace string
	Timestamp int64
	Metrics   []byte
}

func NewSlaveMetrics() *SlaveMetrics {
	return &SlaveMetrics{
		Metrics: []byte{},
	}
}

func (this *SlaveMetrics) Schema() avro.Schema {
	if _SlaveMetrics_schema_err != nil {
		panic(_SlaveMetrics_schema_err)
	}
	return _SlaveMetrics_schema
}

// Generated by codegen. Please do not modify.
var _SlaveMetrics_schema, _SlaveMetrics_schema_err = avro.ParseSchema(`{
    "type": "record",
    "namespace": "avro",
    "name": "SlaveMetrics",
    "fields": [
        {
            "name": "SlaveID",
            "type": "string"
        },
        {
            "name": "Hostname",
            "type": "string"
        },
        {
            "name": "Port",
            "type": "int"
        },
        {
            "name": "Namespace",
            "type": "string"
        },
        {
            "name": "Timestamp",
            "type": "long"
        },
        {
            "name": "Metrics",
            "type": "bytes"
        }
    ]
}`)
